name: Test

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

      # Below will only happen if a release was created
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build artifacts
        run: uv build

      - name: Upload build artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for f in dist/*; do
            echo "Uploading $f"
            gh release upload ${{ steps.release.outputs.tag_name }} "$f"
          done

      - name: Test PyPI publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
